<a href="https://colab.research.google.com/github/Mono-Blaine/CMPS-261-Project/blob/master/261_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor

In [2]:
# Load the dataset
# header=None prevents the first row from becoming column names
data = pd.read_csv('drive/MyDrive/HIGGS_train.csv', header=None)
# columns=['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28',]

<ipython-input-2-515a8d45932e>:3: DtypeWarning: Columns (8,21) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('drive/MyDrive/HIGGS_train.csv', header=None)


# **Preprocessing**

In [5]:
# print(data[8])
# print(data.head())
# data[data.iloc[:, 1:] > 70] 
data=data.select_dtypes(include=['float64'])
data=data.select_dtypes(exclude=['object'])

# data=data.fillna(0)
data=data.dropna()

# Separate the target variable and input features
X = data.iloc[:, 1:]
y = data.iloc[:, 0]

# **Logistic Regression**

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Handle the missing values using Imputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

# Create a logistic regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Predict the target variable for the testing data
y_pred = model.predict(X_test)

# Evaluate the performance of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(cross_val_score(model, X, y, cv=5))

# Accuracy: 0.6412722222222222
# [0.63906667 0.64083333 0.64368333 0.63920833 0.64088333]

Accuracy: 0.6412722222222222
[0.63906667 0.64083333 0.64368333 0.63920833 0.64088333]


# **XGBoost**

In [6]:
scores = cross_val_score(XGBRegressor(), X, y, scoring='neg_mean_squared_error')
scores

array([-0.17749921, -0.17616643, -0.17543016, -0.17692017, -0.17591041])